-- MySQL Script generated by MySQL Workbench
-- mar. 07 févr. 2017 15:55:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rolecraft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rolecraft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rolecraft` DEFAULT CHARACTER SET utf8mb4 ;
USE `rolecraft` ;

-- -----------------------------------------------------
-- Table `rolecraft`.`rc_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolecraft`.`rc_modelsheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_modelsheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `private` TINYINT NULL,
  `language` VARCHAR(45) NOT NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  `mongo_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fa_facture_2_idx` (`user_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_fa_facture_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `rolecraft`.`rc_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolecraft`.`rc_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_section` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelsheet_id` INT(11) NOT NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  `name` VARCHAR(45) NULL,
  `is_separator` INT(11) NULL,
  `size` INT(11) NULL,
  `search_id` VARCHAR(45) NULL,
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rc_modelsheet_sections_1_idx` (`modelsheet_id` ASC),
  CONSTRAINT `fk_rc_modelsheet_sections_1`
    FOREIGN KEY (`modelsheet_id`)
    REFERENCES `rolecraft`.`rc_modelsheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolecraft`.`rc_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_element` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `section_id` INT(11) NOT NULL,
  `label` VARCHAR(45) NULL,
  `search_id` VARCHAR(45) NULL,
  `type` VARCHAR(255) NOT NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  INDEX `fk_rc_element_1_idx` (`section_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rc_element_1`
    FOREIGN KEY (`section_id`)
    REFERENCES `rolecraft`.`rc_section` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolecraft`.`rc_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_table` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rows` INT(11) NULL,
  `cols` INT(11) NULL,
  `element_id` INT(11) NOT NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rc_table_1_idx` (`element_id` ASC),
  CONSTRAINT `fk_rc_table_1`
    FOREIGN KEY (`element_id`)
    REFERENCES `rolecraft`.`rc_element` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rolecraft`.`rc_table_box`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rolecraft`.`rc_table_box` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NULL,
  `table_id` INT(11) NOT NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  `x` INT(2) NOT NULL,
  `y` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rc_case_1_idx` (`table_id` ASC),
  CONSTRAINT `fk_rc_case_1`
    FOREIGN KEY (`table_id`)
    REFERENCES `rolecraft`.`rc_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
